refactor: minor improvements

diff --git a/.github/workflows/create_release.yaml b/.github/workflows/create_release.yaml
--- a/.github/workflows/create_release.yaml
+++ b/.github/workflows/create_release.yaml
@@ -22,8 +22,8 @@ jobs:
           APP_VERSION: ${{ inputs.appVersion }}
         run: |
           if [[ ! "$APP_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-          echo "::error::Invalid appVersion: $APP_VERSION"
-          exit 1
+            echo "::error::Invalid appVersion: $APP_VERSION"
+            exit 1
           fi
 
           IFS='.' read -r major minor patch <<< "$APP_VERSION"
